name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: bitrix
    steps:
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build the Docker image
        run: docker build -t $LOGIN/$NAME:latest -f php7.4/apache/Dockerfile .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:latest